### ISSUE TITLE
 - villia - ERROR - name 'exit' is not defined

### ISSUE THREAD

**Issue by hlfzsi** [avilliai/Petunia#2]
v0.4版本出现 - villia - ERROR - name 'exit' is not defined错误
![捕获](https://github.com/avilliai/Bergml/assets/78413699/97200ed8-8745-4ed0-bc10-534b3b026346)

**Comment by avilliai** [comment]
> v0.4版本出现 - villia - ERROR - name 'exit' is not defined错误 ![捕获](https://private-user-images.githubusercontent.com/78413699/324179442-97200ed8-8745-4ed0-bc10-534b3b026346.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MjIyMzQsIm5iZiI6MTcxMzYyMTkzNCwicGF0aCI6Ii83ODQxMzY5OS8zMjQxNzk0NDItOTcyMDBlZDgtODc0NS00ZWQwLWJjMTAtNTM0YjNiMDI2MzQ2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE0MDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNzBiMWI0MWUxYmE5NmJiZWRjNDIyNmYzZjA0ZmI1YTYwZDhkNzg5MzIzYzdlOGNhYzU1MzRlZGJkZWQyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lYMGEVjno288J5a7-gqSX79bEzAORcqBig8lQNBdsRw)

- 请确保已安装[mirai-api-http](https://github.com/project-mirai/mirai-api-http) 并[正确配置](https://github.com/avilliai/wReply/blob/master/setting.yml)，建议直接用[配置](https://github.com/avilliai/wReply/blob/master/setting.yml)覆盖你本地自己的http-api配置文件
- 请确保Petunia/settings.yaml填写正确
```
bot:
  http-api-key: '1234567890'   #mirai-api-http的verify key(使用[推荐的mirai-api-http/setting.yml]((https://github.com/avilliai/wReply/blob/master/setting.yml))直接覆盖本地对应文件config/mirai-api-http/setting.yml无需修改此项)
  http-api-port: 23456             #mirai-api-http的port(使用[推荐的mirai-api-http/setting.yml]((https://github.com/avilliai/wReply/blob/master/setting.yml))直接覆盖本地对应文件config/mirai-api-http/setting.yml无需修改此项)
  botqq: 3377428814             #机器人的qq，务必与Mirai登陆的机器人qq保持一致
```
